# Generated by Django 5.1.1 on 2025-02-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
    ]
